crashreport : javacrash in StartServiceActivity on attempting to pause
BZ: 202600

[Preloaded Apps] JAVACRASH com.intel.crashreport
java.lang.RuntimeException: Unable to pause activity
Main ideea is: a barier is used (alreadyRegistered) which is static,
and it decides if the local instance(msgReceiver) is
registered/unregistered. The fix is in removing the static define of
(alreadyRegistered). try/catch is simply a defensive implementation.

Change-Id: Ief90564cd7a3ad983f2d0548f1c6af49c30a7794